[tool.briefcase]
project_name = "Run Intervals"
bundle = "com.rkode"
version = "0.0.1"
url = "https://twitter.com/wholemilk"
license = "MIT license"
author = 'Rachel Kelly'
author_email = "intervals@rkode.com"

[tool.briefcase.app.runintervals]
formal_name = "Run Intervals"
description = "The simplest possible interval management mobile application"
icon = "src/runintervals/resources/runintervals"
sources = ['src/runintervals']
requires = []


[tool.briefcase.app.runintervals.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.runintervals.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.runintervals.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.runintervals.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.runintervals.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
